name: Node.js CI

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  build:
    runs-on: [windows-latest, ubuntu-latest, macos-latest]
    strategy:
      matrix:
        node-version: [10.15.x, 10.x, 12.x, 14.x, 15.x]
    steps:
      - uses: actions/checkout@v2
      - name: ${{ runner.OS }}-node-${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm test
